name: Bot

on:
  issues: 
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  assign-security-issue:
    if: ${{ github.event_name == 'issues' }}
    name: Assign Security Label
    env:
      repo: ${{ github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Assign Security Label
        if: ${{ contains(github.event.issue.title, 'security')}}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "security"
  assign-security-pr:
    if: ${{ github.event_name == 'pull_request' }}
    name: Assign Security Label
    env:
      repo: ${{ github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Assign Security Label
        if: ${{ github.event.pull_request.draft == false && contains(github.event.pull_request.title, 'security')}}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.number }} --add-label "security"
  assign-triage-pr:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.author_association  != 'COLLABORATOR' && github.event.pull_request.author_association  != 'OWNER' && !startsWith(github.event.pull_request, 'BUMP')}}
    name: Assign Triage Label
    env:
      repo: ${{ github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Event Debug
        if: false
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.sender.id }}
          echo ${{ github.event.pull_request.author_association }}
      - name: Assign Security Label
        if: ${{ github.event.pull_request.draft == false }}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.number }} --add-label "triage"
  assign-community-pr:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.author_association  != 'COLLABORATOR' && github.event.pull_request.author_association  != 'OWNER' && !startsWith(github.event.pull_request, 'BUMP')}}
    name: Assign Triage Label
    env:
      repo: ${{ github.head_ref }}
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Assign Security Label
        if: ${{ github.event.pull_request.draft == false }}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.number }} --add-label "triage"